# Generated by Django 4.1.1 on 2022-11-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="code",
            field=models.SlugField(default="GP", max_length=2),
        ),
    ]
