# Generated by Django 5.0 on 2023-12-29 16:14

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("terms", "0002_term_created_term_owner_term_updated_topic_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="term",
            name="short_version",
            field=markdownx.models.MarkdownxField(max_length=250),
        ),
    ]
